all:
	gcc 188-Best-Time-to-Buy-and-Sell-Stock-IV.c -o 188
# gcc 121-Best-Time-to-Buy-and-Sell-Stock.c -o 121
# gcc 122-Best-Time-to-Buy-and-Sell-Stock-II_byDP-willTLE.c -o 122TLE
# gcc 122-Best-Time-to-Buy-and-Sell-Stock-II_O-N-time_0ms.c -o 122On
# gcc 123-Best-Time-to-Buy-and-Sell-Stock-III_by121-willTLE.c -o 123TLE
# gcc 123-Best-Time-to-Buy-and-Sell-Stock-III.c -o 123
# gcc 309-Best-Time-to-Buy-and-Sell-Stock-with-Cooldown.c -o 309
# gcc 714-Best-Time-to-Buy-and-Sell-Stock-with-Transaction-Fee.c -o 714
clean:
	-rm *.exe